#!/bin/sh

# The famous "get a menu of emojis to copy" script.
# Made by Luke Smith (https://github.com/LukeSmithxyz/voidrice/blob/master/.local/bin/dmenuunicode)

cat /opt/dwm/scripts/dmenuunicode-chars/* | grep -v "#" | dmenu "$@" -i -l 30 | awk '{print $1}' | tr -d '\n' | xclip -selection clipboard

pgrep -x dunst >/dev/null && notify-send "'$(xclip -o -selection clipboard)' copied to clipboard."
