#!/bin/sh

# The famous "get a menu of emojis to copy" script.
# Made by Luke Smith (https://github.com/LukeSmithxyz/voidrice/blob/master/.local/bin/dmenuunicode)

# Get user selection via dmenu from emoji file.
chosen=$(cut -d ';' -f1 /usr/local/bin/dmenuunicode-chars/* | dmenu "$@" -i -l 30 | sed "s/ .*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit

printf "$chosen" | xclip -selection clipboard
notify-send "'$chosen' copied to clipboard." &
