#!/bin/bash

opt_cancel="  cancel"
opt_poweroff="  poweroff"
opt_reboot="  reboot"
opt_update_poweroff="󰚰  update & $opt_poweroff"
opt_update_reboot="󰚰  update & $opt_reboot"

run_cmd() {
    selected="$1"

    case "$selected" in
        "$opt_poweroff"*) sudo poweroff ;;
        "$opt_reboot"*) sudo reboot ;;
        "$opt_update_poweroff"*) st -e zsh -c 'yay -Syu --noconfirm && sleep 3 && sudo poweroff' ;;
        "$opt_update_reboot"*) st -e zsh -c 'yay -Syu --noconfirm && sleep 3 && sudo reboot' ;;
        "$opt_cancel"*) return ;;
    esac
}

powermenu() {
    pending_updates=$(checkupdates | wc -l)

    options="$opt_cancel\n$opt_poweroff\n$opt_reboot"

    if [[ $pending_updates -ge 50 ]]; then
        options+="\n$opt_update_poweroff ($pending_updates pending updates)\n$opt_update_reboot ($pending_updates pending updates)"
    fi

    selected=$(printf "$options" | dmenu "$@")
    run_cmd "$selected"
}

powermenu "$@"
