#!/bin/bash

powermenu() {
	options="Cancel\nShutdown\nReboot"
	selected=$(echo -e $options | dmenu "$@")
	if [[ $selected = "Shutdown" ]]; then
		poweroff
	elif [[ $selected = "Reboot" ]]; then
		reboot
	elif [[ $selected = "Cancel" ]]; then
		return
	fi
}

powermenu "$@"
